### ISSUE TITLE
[Feature request] Save keys from ManagedGroup in KeyStore

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#345] opened 2021-02-09 18:40 UTC
**Is your feature request related to a problem? Please describe.**
Keys should only be saved in the ne `KeyStore` whenever possible

**Describe the solution you'd like**
`KeyStore` should provide an appropriate API.

**Describe alternatives you've considered**
Keep the keys in `ManagedGroup`

**Additional context**
None

**Comment by kkohbrok** [comment] 2021-02-10 07:52
I believe this is a dupe of #337 and can be closed.

**Closed** 2021-02-10 08:44 UTC
Labels: duplicate, enhancement
