### ISSUE TITLE
Compatibility with pre-release versions

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#641] opened 2021-12-17 16:05 UTC
We currently treat ciphersuites and MLS versions separate. In theory, that allows us to treat different pre-release versions separate from one-another, but we're not really using it in any way. We shoul decide to which degree we want to support pre-release versions, how that separation is implemented and how we use it in tests.

**Comment by kkohbrok** [comment] 2021-12-27 14:10
I filed https://github.com/mlswg/mls-protocol/pull/532, the result of which might yield a way to treat the problem that works across implementations.

**Comment by raphaelrobert** [comment] 2022-02-24 17:09
Duplicate of #628.

**Closed by raphaelrobert** 2022-02-24 17:09 UTC
