### ISSUE TITLE
Better testing for the public and private tree components

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#232] opened 2020-11-26 09:30 UTC
Neither the public- nor the private tree are very well tested. Both have edge cases that warrant better testing.

**Comment by raphaelrobert** [comment] 2020-11-28 18:41
There is a regression in `apply_commit` that was introduced in the last private tree refactoring.
The ratchet tree is not copied initially, instead the modifications of the Commit are directly applied to the original tree, regardless of whether the Commit is valid (which can only be checked once the changes have been applied, hence the need for an independent provisional tree).
Creating a new provisional tree from the public values of the original ratchet tree (as it is done in `create_commit`) does not work, because the existing private tree is needed if the Commit is issued by someone else and their `UpdatePath` needs to be decrypted.
This will most likely mandate a bit of refactoring.

**Comment by franziskuskiefer** [comment] 2020-11-30 09:26
> There is a regression in `apply_commit` that was introduced in the last private tree refactoring.

@raphaelrobert  Is there a bug for this?

**Comment by raphaelrobert** [comment] 2020-11-30 09:30
Do you mean an issue? I didn't create a separate issue. @kkohbrok wanted to start working on this anyway and this is just some context of what I found out.

**Comment by franziskuskiefer** [comment] 2020-11-30 10:11
But this is a testing issue. Then we should either change this one to a bug fix or add a separate one that's addressing the issue.

**Comment by raphaelrobert** [comment] 2024-02-11 20:33
This is now pretty old and the tree-related code has been refactored since. I'll close this since it's too vague.

@kkohbrok feel free to re-open with more actionable specifics if you think this is still relevant.

**Closed by raphaelrobert** 2024-02-11 20:33 UTC
Labels: tests
