### ISSUE TITLE
[MLS Spec change] Fix typo in Parent Hash verification

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#474] opened 2021-10-04 09:13 UTC
**Description of the changes**
Fix typo in Parent Hash verification 

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/460

**Comment by kkohbrok** [comment] 2021-10-04 10:47
Dupe of #380?

**Comment by raphaelrobert** [comment] 2021-10-04 10:50
If you are sure this change has been implemented, you can close.

**Comment by kkohbrok** [comment] 2021-10-04 10:55
This was indeed fixed. See here specifically: https://github.com/openmls/openmls/pull/390/files#diff-f483c527ae14a7bfefeb3ee2a1e2eefec1cba21c7295f35e374d407dd5f56ea1R240.

**Closed by kkohbrok** 2021-10-04 10:55 UTC
Labels: mls-spec change
