### ISSUE TITLE
[MLS Spec change] Use smaller, fixed-size hash-based identifiers (#510)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#985] opened 2022-10-11 13:43 UTC
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/510

**Description of the changes**
> Fixes #506 
 > Fixes #504

**Comment by franziskuskiefer** [comment] 2022-10-11 17:21
Duplicate of #541

**Closed by franziskuskiefer** 2022-10-11 17:21 UTC
Labels: mls-spec change
