### ISSUE TITLE
[MLS Spec change] Forbid self-Update entirely (#519)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#992] opened 2022-10-11 13:43 UTC
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/519

**Description of the changes**
> Fixes #516

**Comment by franziskuskiefer** [comment] 2022-10-11 17:47
duplicate of #663

**Closed by franziskuskiefer** 2022-10-11 17:47 UTC
Labels: mls-spec change
