### ISSUE TITLE
[Feature request] self_update() should take Option<LeafNode>

### ISSUE THREAD

**Issue by SimonThormeyer** [openmls/openmls#1248] opened 2023-02-03 12:29 UTC
**Is your feature request related to a problem? Please describe.**

https://github.com/openmls/openmls/blob/692debcef1012271652cf28c7fe6dce169e5c120/openmls/src/group/mls_group/updates.rs#L24-L28

and 

https://github.com/openmls/openmls/blob/692debcef1012271652cf28c7fe6dce169e5c120/openmls/src/group/mls_group/updates.rs#L65-L70

take a different list of arguments. For our use case, we would like `self_update()` to take the optional `LeafNode` argument as well, to allow updating a signature key without proposing and commiting separately.

**Comment by kkohbrok** [comment] 2023-02-07 08:57
I looked into this and it's somewhat non-trivial due to the way we handle leaf nodes during commit processing. The latter needs an overhaul anyway, so I'd like to take this opportunity to generally refactor commit creation a little. I'll take care of this when I merge the changes I already made in the `konrad/public_group_api` to `main` to avoid unnecessary conflicts.

**Comment by raphaelrobert** [comment] 2023-04-13 18:54
Duplicate of #1208.

**Closed by raphaelrobert** 2023-04-13 18:54 UTC
Labels: enhancement, api
